"""TLS certificate management and nginx configuration — REQ-14 (self-signed), REQ-15 (Let's Encrypt)."""

import ipaddress
import os
import shutil
import subprocess
import sys
from pathlib import Path

from . import log
from .exitcodes import EXIT_TLS

_DEFAULT_CERT_DIR    = Path("/etc/ssl/nextcloud")
_DEFAULT_SERVER_NAME = "localhost"

_NGINX_AVAILABLE = Path("/etc/nginx/sites-available/nextcloud")
_NGINX_ENABLED   = Path("/etc/nginx/sites-enabled/nextcloud")
_NGINX_DEFAULT   = Path("/etc/nginx/sites-enabled/default")

# nginx config template — ALL_CAPS tokens are substituted by _nginx_config_str().
# Raw string so Python doesn't interpret nginx regex sequences (e.g. \.) as escapes.
# nginx's own $variables need no escaping either since Python raw strings preserve $.
_NGINX_CONF_TMPL = r"""
# Nextcloud nginx configuration — generated by nextcloud-installer (REQ-14)
# DO NOT EDIT: regenerated on each installer run.

upstream php-handler {
    server unix:PHP_FPM_SOCK;
}

# HTTP → HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name NGINX_SERVER_NAME;
    return 301 https://$host$request_uri;
}

# HTTPS server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name NGINX_SERVER_NAME;

    root NEXTCLOUD_WEB_ROOT;
    index index.php index.html;

    ssl_certificate     SSL_CERT_PATH;
    ssl_certificate_key SSL_KEY_PATH;
    ssl_session_timeout 1d;
    ssl_session_cache   shared:MozSSL:10m;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    client_max_body_size 512M;
    client_body_timeout  300s;
    fastcgi_buffers      64 4K;

    gzip on;
    gzip_vary on;
    gzip_comp_level 4;
    gzip_min_length 256;
    gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
    gzip_types application/atom+xml text/javascript application/javascript
        application/json application/ld+json application/manifest+json
        application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject
        application/wasm application/x-font-ttf application/xhtml+xml application/xml
        font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest
        text/css text/plain text/vcard text/vtt text/x-component
        text/x-cross-domain-policy;

    add_header Referrer-Policy                   "no-referrer"       always;
    add_header X-Content-Type-Options            "nosniff"           always;
    add_header X-Frame-Options                   "SAMEORIGIN"        always;
    add_header X-Permitted-Cross-Domain-Policies "none"              always;
    add_header X-Robots-Tag                      "noindex, nofollow" always;
    add_header X-XSS-Protection                  "1; mode=block"     always;
    add_header Strict-Transport-Security         "max-age=15768000; includeSubDomains; preload;" always;

    fastcgi_hide_header X-Powered-By;

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log    off;
    }

    location ^~ /.well-known {
        location = /.well-known/carddav { return 301 /remote.php/dav/; }
        location = /.well-known/caldav  { return 301 /remote.php/dav/; }
        location /.well-known/acme-challenge { try_files $uri $uri/ =404; }
        location /.well-known/pki-validation { try_files $uri $uri/ =404; }
        return 301 /index.php$request_uri;
    }

    location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)(?:$|/) { return 404; }
    location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console)               { return 404; }

    location ~ \.php(?:$|/) {
        rewrite ^/(?!index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|ocs-provider\/.+|.+\/richdocumentscode\/proxy) /index.php$request_uri;
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        set $path_info $fastcgi_path_info;
        try_files $fastcgi_script_name =404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME         $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO               $path_info;
        fastcgi_param HTTPS                   on;
        fastcgi_param modHeadersAvailable     true;
        fastcgi_param front_controller_active true;
        fastcgi_pass              php-handler;
        fastcgi_intercept_errors  on;
        fastcgi_request_buffering off;
        fastcgi_max_temp_file_size 0;
    }

    location ~ \.(?:css|js|woff2?|svg|gif|map)$ {
        try_files $uri /index.php$request_uri;
        add_header Cache-Control "public, max-age=15778463";
        access_log off;
    }

    location ~ \.(?:png|html|ttf|ico|jpg|jpeg|bcmap|mp4|webm)$ {
        try_files $uri /index.php$request_uri;
        access_log off;
    }

    location / {
        try_files $uri /index.php$request_uri;
    }
}
"""


def _nginx_config_str(
    web_root: Path,
    php_ver: str,
    cert_path: Path,
    key_path: Path,
    server_name: str,
) -> str:
    fpm_sock = f"/var/run/php/php{php_ver}-fpm.sock"
    return (
        _NGINX_CONF_TMPL.lstrip("\n")
        .replace("PHP_FPM_SOCK",       fpm_sock)
        .replace("NGINX_SERVER_NAME",  server_name)
        .replace("NEXTCLOUD_WEB_ROOT", str(web_root))
        .replace("SSL_CERT_PATH",      str(cert_path))
        .replace("SSL_KEY_PATH",       str(key_path))
    )


def _is_local_domain(server_name: str) -> bool:
    """Return True when server_name is localhost or a bare IP address.

    Let's Encrypt HTTP-01 requires a public FQDN; these names must use self-signed.
    """
    if server_name == "localhost":
        return True
    try:
        ipaddress.ip_address(server_name)
        return True
    except ValueError:
        return False


def _install_certbot() -> None:
    """Install the certbot package if it is not already on PATH."""
    if shutil.which("certbot"):
        return
    log.info("[TLS] Installing certbot ...")
    r = subprocess.run(
        ["apt-get", "install", "-y", "certbot"],
        env={**os.environ, "DEBIAN_FRONTEND": "noninteractive"},
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        log.error(f"[TLS] ERROR: certbot install failed:\n{r.stderr.strip()}")
        sys.exit(EXIT_TLS)
    log.ok("[TLS] certbot installed.")


def _run_certbot_standalone(domain: str, email: str) -> tuple[Path, Path]:
    """REQ-15: Obtain a Let's Encrypt certificate via the standalone HTTP-01 challenge.

    Idempotent: skips the certbot invocation if live cert files already exist.
    Caller must stop nginx before this call so certbot can bind port 80.
    Returns (fullchain_path, privkey_path).
    """
    cert_dir  = Path(f"/etc/letsencrypt/live/{domain}")
    cert_path = cert_dir / "fullchain.pem"
    key_path  = cert_dir / "privkey.pem"

    if cert_path.exists() and key_path.exists():
        log.ok(f"[TLS] Let's Encrypt certificate already present for {domain} — skipping.")
        return cert_path, key_path

    log.info(f"[TLS] Requesting Let's Encrypt certificate for {domain} ...")
    r = subprocess.run(
        [
            "certbot", "certonly",
            "--standalone",
            "--non-interactive",
            "--agree-tos",
            "--email", email,
            "-d", domain,
        ],
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        combined = "\n".join(filter(None, [r.stderr.strip(), r.stdout.strip()]))
        log.error(f"[TLS] ERROR: certbot failed:\n{combined}")
        sys.exit(EXIT_TLS)

    log.ok(f"[TLS] Let's Encrypt certificate obtained for {domain}.")
    return cert_path, key_path


def generate_self_signed(cert_dir: Path, cn: str) -> tuple[Path, Path]:
    """REQ-14: Generate a self-signed RSA-4096 certificate valid for 10 years.

    Idempotent — skips generation if both files already exist.
    Returns (cert_path, key_path).
    """
    cert_path = cert_dir / "cert.pem"
    key_path  = cert_dir / "key.pem"

    if cert_path.exists() and key_path.exists():
        log.ok("[TLS] Self-signed certificate already present — skipping generation.")
        return cert_path, key_path

    cert_dir.mkdir(parents=True, exist_ok=True)
    log.info(f"[TLS] Generating self-signed certificate (CN={cn}) ...")

    r = subprocess.run(
        [
            "openssl", "req", "-x509",
            "-newkey", "rsa:4096",
            "-keyout", str(key_path),
            "-out",    str(cert_path),
            "-days",   "3650",
            "-nodes",
            "-subj",   f"/CN={cn}",
        ],
        capture_output=True,
        text=True,
    )
    if r.returncode != 0:
        log.error(f"[TLS] ERROR: openssl failed:\n{r.stderr.strip()}")
        sys.exit(EXIT_TLS)

    cert_path.chmod(0o644)
    key_path.chmod(0o600)
    log.ok(f"[TLS] Self-signed certificate written to {cert_dir}.")
    return cert_path, key_path


def _write_nginx_config(
    web_root: Path,
    php_ver: str,
    cert_path: Path,
    key_path: Path,
    server_name: str,
) -> None:
    """Write the nginx site config, remove the default site, and create the enabled symlink."""
    config = _nginx_config_str(web_root, php_ver, cert_path, key_path, server_name)

    _NGINX_AVAILABLE.parent.mkdir(parents=True, exist_ok=True)
    _NGINX_AVAILABLE.write_text(config)
    log.ok(f"[TLS] nginx config written to {_NGINX_AVAILABLE}.")

    if _NGINX_DEFAULT.exists() or _NGINX_DEFAULT.is_symlink():
        _NGINX_DEFAULT.unlink()
        log.info("[TLS] Removed default nginx site.")

    if _NGINX_ENABLED.is_symlink():
        _NGINX_ENABLED.unlink()
    _NGINX_ENABLED.symlink_to(_NGINX_AVAILABLE)
    log.ok(f"[TLS] nginx site enabled ({_NGINX_ENABLED}).")


def _reload_nginx() -> None:
    """Test the nginx configuration then reload-or-restart the service."""
    log.info("[TLS] Testing nginx configuration ...")
    r = subprocess.run(["nginx", "-t"], capture_output=True, text=True)
    if r.returncode != 0:
        log.error(f"[TLS] ERROR: nginx configuration test failed:\n{r.stderr.strip()}")
        sys.exit(EXIT_TLS)
    log.ok("[TLS] nginx configuration is valid.")

    for cmd in (
        ["systemctl", "enable", "nginx"],
        ["systemctl", "reload-or-restart", "nginx"],
    ):
        r = subprocess.run(cmd, capture_output=True, text=True)
        if r.returncode != 0:
            log.error(f"[TLS] ERROR: {' '.join(cmd)} failed:\n{r.stderr.strip()}")
            sys.exit(EXIT_TLS)

    log.ok("[TLS] nginx is active.")


def run_all(
    web_root: Path,
    php_ver: str,
    server_name: str,
    email: str | None = None,
) -> None:
    """REQ-14 / REQ-15: Configure TLS and the nginx site config.

    Self-signed (REQ-14): used when server_name is localhost or a bare IP.
    Let's Encrypt (REQ-15): used when server_name is a public FQDN; requires --email.

    The nginx config is always rewritten (deterministic) and nginx is reloaded.
    """
    log.info(f"[TLS] Configuring TLS for '{server_name}' ...")

    if _is_local_domain(server_name):
        cert_path, key_path = generate_self_signed(_DEFAULT_CERT_DIR, cn=server_name)
        _write_nginx_config(web_root, php_ver, cert_path, key_path, server_name)
        _reload_nginx()
        log.ok(
            f"[TLS] Done. Nextcloud will be reachable at https://{server_name}/ "
            "(browser security warning expected for self-signed cert)."
        )
    else:
        # REQ-15: Let's Encrypt HTTP-01 via certbot --standalone.
        if not email:
            log.error(
                "[TLS] ERROR: --email is required when using a public domain "
                "with Let's Encrypt (REQ-15)."
            )
            sys.exit(EXIT_TLS)
        _install_certbot()
        # Stop nginx so certbot --standalone can bind port 80 for the ACME challenge.
        subprocess.run(["systemctl", "stop", "nginx"], capture_output=True, text=True)
        cert_path, key_path = _run_certbot_standalone(server_name, email)
        _write_nginx_config(web_root, php_ver, cert_path, key_path, server_name)
        _reload_nginx()
        log.ok(f"[TLS] Done. Nextcloud will be reachable at https://{server_name}/")
